import type { Metadata } from "next";
const guides: Record<string, { title: string; lead: string; sections: Array<[string,string]> }> = {
  hajimete: { title: "初めての作品選びガイド", lead: "画像や煽り文句ではなく、目的・時間・価格・雰囲気の順に整理すると選びやすくなります。", sections: [["結論","最初に『何を見たいか』より『どんな時間を過ごしたいか』を決めます。公式情報、編集部の評価、利用者の声は別々に確認してください。"],["確認する5項目","配信状況、価格、収録時間、シリーズ情報、公式ページの注意事項を確認します。"],["合わない可能性","刺激の強さや具体的内容を求める場合、このサイトの画像を抑えた比較方法は合わないことがあります。"]] },
  privacy: { title: "プライバシーを守る選び方", lead: "好みは機微な情報です。本人が選んだタグだけを端末内で使い、履歴を自分で消せることが基本です。", sections: [["結論","共有端末では好みタグを利用後に消去し、外部広告への送信を許可しないサービスを選びます。"],["当サイトの方針","アカウントへ紐付けず、未選択属性を推測せず、推薦理由を表示します。"],["注意点","リンク先の公式サービスでは別のプライバシーポリシーが適用されます。"]] },
  "ranking-policy": { title: "ランキングとおすすめの方針", lead: "報酬額ではなく、選ばれた好み、掲載前に確認した利用者の声、作品の特徴、情報の新しさを基準にします。", sections: [["順位の決め方","次に選ばれた作品、好みの一致、利用者の声、作品の特徴、情報の新しさを組み合わせ、広告報酬は順位に使いません。"],["表示する理由","一致した好み、選ばれた理由、参考にした人数と期間を表示し、『興味なし』で調整できるようにします。"],["参考値の扱い","十分な利用実績がない段階の数値は参考例と明記し、実績のようには表示しません。"]] }
};
export function generateStaticParams(){ return Object.keys(guides).map(slug=>({slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const g=guides[slug]; return { title:g?.title??"ガイド", description:g?.lead, alternates:{canonical:`/guides/${slug}`} }; }
export default async function Guide({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const g=guides[slug]??guides.hajimete; const base=process.env.SITE_URL??"https://fanza-sdk.example.com"; const ld={"@context":"https://schema.org","@type":"Article",headline:g.title,description:g.lead,datePublished:"2026-07-15",dateModified:"2026-07-15",author:{"@type":"Organization",name:"FANZA GUIDE LAB 編集部"},mainEntityOfPage:`${base}/guides/${slug}`}; return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(ld)}}/><nav className="policyNav"><a href="/">トップ</a><a href="/policies/editorial">編集方針</a></nav><article className="policyShell"><p className="eyebrow">PRACTICAL GUIDE</p><h1>{g.title}</h1><p>{g.lead}</p>{g.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}<p>執筆・確認：FANZA GUIDE LAB編集部　公開・更新：2026年7月15日</p></article></> }
