"use client";
import { useRef, useState } from "react";
const axes = ["ストーリー", "価格", "長さ", "雰囲気", "公式情報の分かりやすさ"];
const audiences = ["初めて選ぶ人", "ストーリー重視", "短時間で選びたい人", "価格重視", "新しい好みを探す人", "その他"];
export function UgcForm() {
  const startedAt = useRef(Date.now()); const [message, setMessage] = useState(""); const [length, setLength] = useState(0);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage("送信中…"); const form = new FormData(event.currentTarget); const response = await fetch("/api/reviews", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...Object.fromEntries(form.entries()), startedAt: startedAt.current }) }); const data = await response.json(); setMessage(data.message ?? data.error); if (response.ok) { event.currentTarget.reset(); setLength(0); startedAt.current = Date.now(); } }
  return <section className="ugcCenter section" id="review-form"><div className="sectionHead"><p className="eyebrow">あなたの声を届ける</p><h2>次の人の判断材料に。</h2><p>満足度だけでなく「何が役立ったか」「誰に向くか」を投稿できます。内容を確認してから掲載します。</p></div><div className="reviewPrinciples"><span>個人情報は不要</span><span>掲載前に内容を確認</span><span>広告報酬と評価を分離</span><span>ネタバレを明示</span></div><form onSubmit={submit}><input type="hidden" name="productId" value="general" /><label className="honey">ウェブサイト<input name="website" tabIndex={-1} autoComplete="off" /></label><div className="reviewFields"><label>最も役立った点<select name="helpfulAxis" required defaultValue=""><option value="" disabled>選択してください</option>{axes.map(x=><option key={x}>{x}</option>)}</select></label><label>満足度<select name="rating" required defaultValue=""><option value="" disabled>選択してください</option>{[5,4,3,2,1].map(x=><option key={x} value={x}>{x} / 5</option>)}</select></label><label>年代（任意）<select name="ageBand" defaultValue="回答しない">{["回答しない", "20代", "30代", "40代", "50代以上"].map(x=><option key={x}>{x}</option>)}</select></label><label>どんな人に向く？<select name="bestFor" required defaultValue=""><option value="" disabled>選択してください</option>{audiences.map(x=><option key={x}>{x}</option>)}</select></label></div><label>選ぶときに役立った具体的な理由<textarea name="body" required minLength={20} maxLength={400} onChange={e=>setLength(e.currentTarget.value.length)} placeholder="例：あらすじと収録時間が整理されていて、公式サイトで確認してから選べました。" /><span className="charCount">{length} / 400文字</span></label><label className="checkLabel"><input type="checkbox" name="containsSpoiler" /> 内容にネタバレを含みます</label><button>投稿内容を送る</button><small>URL、連絡先、個人情報、誹謗中傷、権利侵害、迷惑投稿、具体的すぎる性的表現は掲載しません。投稿内容は編集方針に沿って確認し、必要に応じて非公開にします。</small></form><p className="formMessage" aria-live="polite">{message}</p></section>;
}
